### ISSUE TITLE
Update for Laravel 7

### ISSUE THREAD

**Issue by youngbobby** [tpenaranda/bcoin-laravel#1]
Thanks for this package. Could you please make it compatible with latest Laravel 7? Would highly appreciate that.

**Comment by youngbobby** [comment]
Possible?

**Comment by tpenaranda** [comment]
> Thanks for this package. Could you please make it compatible with latest Laravel 7? Would highly appreciate that.

Ohh, sorry men, this is an abandoned project. @youngbobby
